name: myenv
channels:
  - snowflake
dependencies: 
  # Dependencies of sqlfluff here
  - pytest
  - tblib
  - importlib_resources
  - appdirs
  - toml
  - tqdm
  - jinja2
  - regex
  - pathspec
  - chardet
  # Dependencies of snowflake-sqlalchemy here
  - sqlalchemy
